Repository googleapis/gapic-showcase, pull requests merged in 2021-04, with the labels that each got.

#662 chore: fix collision with operation helper
  util/compile_protos.go
Labels: cla: yes

#668 feat: Ensure enum fields are received as string values over REST transport
  cmd/gapic-showcase/compliance_suite_errors_test.go
  cmd/gapic-showcase/compliance_suite_test.go
  schema/google/showcase/v1beta1/compliance.proto
  schema/google/showcase/v1beta1/compliance_suite.json
  util/genrest/goview/goview.go
  util/genrest/goviewcreator.go
  util/genrest/resttools/checkrestbody.go
  util/genrest/resttools/checkrestbody_test.go
  util/genrest/resttools/populatefield.go
Labels: cla: yes

#674 feat: Ensure full body responses from REST endpoints
  cmd/gapic-showcase/endpoint_test.go
  util/genrest/goviewcreator.go
  util/genrest/resttools/json.go
Labels: cla: yes

#680 Enforce lower-camel-cased field names in REST bodies and query params
  cmd/gapic-showcase/compliance_suite_errors_test.go
  cmd/gapic-showcase/compliance_suite_test.go
  cmd/gapic-showcase/endpoint_test.go
  util/genrest/goviewcreator.go
  util/genrest/resttools/checkrestbody.go
  util/genrest/resttools/checkrestbody_test.go
  util/genrest/resttools/json.go
  util/genrest/resttools/populatefield.go
  util/genrest/resttools/populatefield_test.go
Labels: cla: yes, priority: p1

#688 chore: add new runtime dep and mod tidy
  go.mod
  go.sum
Labels: automerge, cla: yes

#689 chore: draft v0.14.0 release
  CHANGELOG.md
  README.md
  cmd/gapic-showcase/version.go
  util/cmd/bump_version/main.go
Labels: cla: yes

#690 chore: Minor tweaks to RELEASING.md for helpfulness and safety.
  RELEASING.md
Labels: cla: yes

#692 feat: Enforce Content-Type: application/json in REST requests with a body
  cmd/gapic-showcase/compliance_suite_errors_test.go
  cmd/gapic-showcase/compliance_suite_test.go
  cmd/gapic-showcase/endpoint_test.go
  util/genrest/goviewcreator.go
  util/genrest/resttools/checkrequestformat.go
  util/genrest/resttools/checkrequestformat_test.go
  util/genrest/resttools/headers.go
Labels: cla: yes

#694 chore: Add error identifiers and use them in tests
  cmd/gapic-showcase/compliance_suite_errors_test.go
  util/genrest/goviewcreator.go
  util/genrest/resttools/checkrequestformat.go
  util/genrest/resttools/populatefield.go
Labels: cla: yes
